apiVersion: v1
appVersion: "1.0"
description: inlets-operator for Kubernetes
name: inlets-operator
version: 0.4.1
keywords:
- networking
- tunnels
maintainers:
- name: alexellis
  email: alex@openfaas.com
