apiVersion: v1
appVersion: "1.0"
description: inlets-operator for Kubernetes
name: inlets-operator
version: 0.17.11
keywords:
- networking
- loadbalancer
- ingress
- selfhosting
- tunnels
- inlets
maintainers:
- name: alexellis
  email: alex@openfaas.com
- name: han
  email: han@openfaas.com
