apiVersion: v1
appVersion: "1.0"
description: inlets-operator for Kubernetes
name: inlets-operator
version: 0.7.1
keywords:
- networking
- tunnels
- inlets
maintainers:
- name: alexellis
  email: alex@openfaas.com
