replicaCount: 1

provider: "digitalocean"
region: "lon1"

# provider: "gce"
# zone: "us-central1-a"
# gceProjectId: "<Your GCP Project ID>"

#provider: "packet"
#region: "ams1"
# packetProjectId: "project-id"
accessKeyFile: "/var/secrets/inlets/inlets-access-key"

# Obtain a free 14-day trial from https://github.com/inlets/inlets-pro
inletsProLicense: ""

annotatedOnly: false

image: "inlets/inlets-operator:0.6.3"
pullPolicy: "IfNotPresent"
clientImage: "inlets/inlets:2.6.4"
proClientImage: "inlets/inlets-pro:0.5.1"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
