replicaCount: 1

provider: "digitalocean"
region: "lon1"

#provider: "packet"
#region: "ams1"
# packetProjectId: "project-id"
accessKeyFile: "/var/secrets/inlets/inlets-access-key"

# Obtain from https://github.com/alexellis/inlets-pro-pkg
inletsProLicense: ""

annotatedOnly: false

image: "inlets/inlets-operator:0.4.5"
pullPolicy: "IfNotPresent"
clientImage: "inlets/inlets:2.6.1"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
