replicaCount: 1

# inlets PRO enables L4 TCP LoadBalancers in Kubernetes
## Purchase from https://inlets.dev/pricing
inletsProLicense: ""

provider: "digitalocean"
region: "lon1"

#plan: <The plan or size for your cloud instance>

# provider: "gce"
# zone: "us-central1-a"
# projectID: "<Your GCP Project ID>"

# provider: "equinix-metal"
# region: "am6"
# projectID: "<Your equinix-metal Project ID>"

# provider: "scaleway"
# region: "ams1"
# organizationID: "<Your Organization ID>"

# provider: "hetzner"
# region: "fsn1"

accessKeyFile: "/var/secrets/inlets/inlets-access-key"

# Set to /var/secrets/inlets/secret/inlets-secret-key for a provider
# that requires an access key and secret key, such as EC2.
secretKeyFile: ""

# The VPC ID to create the exit-server in (EC2)
vpcId: ""

# The Subnet ID where the exit-server should be placed (EC2)
subnetId: ""

# Only provide LoadBalancers for Services annotated with "dev.inlets.manage=true"
annotatedOnly: false

image: "ghcr.io/inlets/inlets-operator:0.16.2"
pullPolicy: "IfNotPresent"

# These should match
inletsClientImage: "ghcr.io/inlets/inlets-pro:0.9.9"
inletsRelease: "0.9.9"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
