replicaCount: 1

# You must create a secret called "inlets-license"

# kubectl create secret generic -n inlets \
# inlets-license --from-file license=$HOME/.inlets/LICENSE

provider: "digitalocean"
region: "lon1"

# Only provide LoadBalancers for Services annotated with "operator.inlets.dev/manage=1"
# Required when using a network driver that uses IPVS instead of iptables
annotatedOnly: false

# These two versions should match for the client and server
# For the client which will run as a Deployment in Kubernetes
inletsClient:
  image: "ghcr.io/inlets/inlets-pro:0.9.32"

# For the server which will run a binary via systemd
inletsRelease: "0.9.32"

#plan: <The plan or size for your cloud instance>

# provider: "gce"
# zone: "us-central1-a"
# projectID: "<Your GCP Project ID>"

# provider: "equinix-metal"
# region: "am6"
# projectID: "<Your equinix-metal Project ID>"

# provider: "scaleway"
# region: "ams1"
# organizationID: "<Your Organization ID>"

# provider: "hetzner"
# region: "fsn1"

accessKeyFile: "/var/secrets/inlets/inlets-access-key"

# Set to /var/secrets/inlets/secret/inlets-secret-key for a provider
# that requires an access key and secret key, such as EC2.
secretKeyFile: ""

# The VPC ID to create the exit-server in (EC2)
vpcId: ""

# The Subnet ID where the exit-server should be placed (EC2)
subnetId: ""

image: "ghcr.io/inlets/inlets-operator:0.17.9"
pullPolicy: "IfNotPresent"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

# Set a maximum memory limit for the inlets client Deployments
maxClientMemory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
