replicaCount: 1

provider: "digitalocean"
region: "lon1"

# provider: "gce"
# zone: "us-central1-a"
# projectID: "<Your GCP Project ID>"

# provider: "packet"
# region: "ams1"
# projectID: "<Your Packet Project ID>"

# provider: "scaleway"
# region: "ams1"
# organization-id: "<Your Organization ID>"

accessKeyFile: "/var/secrets/inlets/inlets-access-key"

# Set to /var/secrets/inlets/secret/inlets-secret-key for a provider that requires an access key and secret key, such as EC2
secretKeyFile: ""

# Obtain a free 14-day trial from https://github.com/inlets/inlets-pro
inletsProLicense: ""

annotatedOnly: false

image: "inlets/inlets-operator:0.6.6"
pullPolicy: "IfNotPresent"
clientImage: "inlets/inlets:2.6.4"
proClientImage: "inlets/inlets-pro:0.5.6"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
