replicaCount: 1

# inlets PRO enables L4 TCP LoadBalancers in Kubernetes
## To enable, obtain a free 14-day trial from https://github.com/inlets/inlets-pro
## Or purchase at https://store.openfaas.com/
inletsProLicense: ""

provider: "digitalocean"
region: "lon1"

# provider: "gce"
# zone: "us-central1-a"
# projectID: "<Your GCP Project ID>"

# provider: "equinix-metal"
# region: "ams1"
# projectID: "<Your equinix-metal Project ID>"

# provider: "scaleway"
# region: "ams1"
# organizationID: "<Your Organization ID>"

# provider: "hetzner"
# region: "fsn1"

accessKeyFile: "/var/secrets/inlets/inlets-access-key"

# Set to /var/secrets/inlets/secret/inlets-secret-key for a provider
# that requires an access key and secret key, such as EC2.
secretKeyFile: ""

# The VPC ID to create the exit-server in (EC2)
vpcId: ""

# The Subnet ID where the exit-server should be placed (EC2)
subnetId: ""

# Only provide LoadBalancers for Services annotated with "dev.inlets.manage=true"
annotatedOnly: false

image: "ghcr.io/inlets/inlets-operator:0.12.3"
pullPolicy: "IfNotPresent"
proClientImage: "ghcr.io/inlets/inlets-pro:0.8.4"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
